export const features = [
  {
    id: "voice",
    icon: "🎤",
    title: "Voice Input / Output",
    color: "#6366f1",
    glow: "rgba(99,102,241,0.4)",
    badge: "Web Speech API",
    desc: "Speak your questions, hear AI answers",
    details: ["Click mic → speak your question", "AI response read aloud via TTS", "Hands-free engineering study", "Supports all tool modes"],
  },
  {
    id: "pdf",
    icon: "📄",
    title: "PDF Upload & Summarize",
    color: "#0891b2",
    glow: "rgba(8,145,178,0.4)",
    badge: "pdfjs-dist",
    desc: "Upload any PDF, get AI-powered notes",
    details: ["Drag & drop PDF upload", "Extracts text client-side", "Auto-summarize / generate notes", "Create flashcards from PDF"],
  },
  {
    id: "gamification",
    icon: "🏆",
    title: "Gamification & Badges",
    color: "#d97706",
    glow: "rgba(217,119,6,0.4)",
    badge: "XP System",
    desc: "Earn XP, level up, unlock badges",
    details: ["XP per tool use & quiz score", "4 levels: Novice → Master", "12 unique achievement badges", "Weekly XP leaderboard"],
  },
  {
    id: "revision",
    icon: "📅",
    title: "Smart Revision Scheduler",
    color: "#059669",
    glow: "rgba(5,150,105,0.4)",
    badge: "SM-2 Algorithm",
    desc: "Spaced repetition for long-term memory",
    details: ["Cards scheduled: 1→3→7→14→30d", "Rate recall: Easy / Hard / Again", "Calendar view of due cards", "Streak tracking & reminders"],
  },
  {
    id: "collab",
    icon: "👥",
    title: "Collaborative Study Rooms",
    color: "#7c3aed",
    glow: "rgba(124,58,237,0.4)",
    badge: "Socket.IO",
    desc: "Study together in real-time rooms",
    details: ["Create room with invite code", "Share AI outputs live", "See who's online & active tool", "Room chat + shared whiteboard"],
  },
  {
    id: "theme",
    icon: "🌙",
    title: "Dark / Light Theme",
    color: "#be185d",
    glow: "rgba(190,24,93,0.4)",
    badge: "CSS Variables",
    desc: "Switch themes with smooth transition",
    details: ["One-click dark/light toggle", "Persists across sessions", "Smooth 300ms CSS transition", "Custom accent color picker"],
  },
  {
    id: "mindmap",
    icon: "🧠",
    title: "AI Mind Map Builder",
    color: "#0d9488",
    glow: "rgba(13,148,136,0.4)",
    badge: "D3.js + GPT",
    desc: "Auto-generate visual mind maps from topics",
    details: ["Topic → full concept map", "Drag & rearrange nodes", "Export as PNG / SVG", "Link concepts to flashcards"],
  },
  {
    id: "codelab",
    icon: "💻",
    title: "Live Code Lab",
    color: "#ea580c",
    glow: "rgba(234,88,12,0.4)",
    badge: "Monaco + WASM",
    desc: "Run code in-browser, get AI code reviews",
    details: ["Python / JS / C++ sandbox", "AI explains errors inline", "Step-through debugger", "Challenge mode with test cases"],
  },
  {
    id: "analytics",
    icon: "📊",
    title: "Learning Analytics",
    color: "#9333ea",
    glow: "rgba(147,51,234,0.4)",
    badge: "Recharts + ML",
    desc: "Deep insights into your study patterns",
    details: ["Heatmap of study sessions", "Weak topic detection", "Predicted exam readiness %", "Personalized study plan AI"],
  },
  {
    id: "interview",
    icon: "🎯",
    title: "Mock Interview Mode",
    color: "#dc2626",
    glow: "rgba(220,38,38,0.4)",
    badge: "AI Evaluator",
    desc: "Simulate real technical interviews with AI",
    details: ["Timed Q&A sessions", "AI grades your answers 0–10", "Hint system & model answers", "Generates custom question bank"],
  },
];

export const GROUPS = [
  { label: "Core Features", ids: ["voice", "pdf", "gamification", "revision", "collab", "theme"] },
  { label: "Advanced", ids: ["mindmap", "codelab", "analytics", "interview"], isNew: true },
];
